"""DispatchContext and DispatchReceipt — non-forgeable authority receipts.

Phase 09C Correction Round 4 — verified-client execution receipt & idempotency key.

Design invariants:
  - DispatchContext binds: endpoint, contract, calculation_type, project_id, snapshot_id,
    work_item_id, evidence_digest, request_digest, expected_unit, idempotency_key.
  - DispatchReceipt is VERIFIED ONLY if issued by CoreEngineCalculationClient.execute_dispatch().
    Public/caller construction produces an unverified receipt (verification_token=None).
  - is_authority_valid() rejects any unverified receipt, malformed response shape,
    unit mismatch, or identity mismatch (project_id/snapshot_id/idempotency_key if echoed).
"""
from __future__ import annotations

import hashlib
import json
import uuid
from typing import Any, Optional
from pydantic import BaseModel, Field, ValidationError

from .dispatch_schemas import DICalculationsResponse, DIManualTakeoffResponse


class DispatchContext(BaseModel):
    """Immutable record created by build_engine_dispatch() after validation."""
    endpoint: str
    contract: Optional[str] = None          # e.g. "takeoff.mep"
    calculation_type: Optional[str] = None  # e.g. "concrete_column_total_volume"
    project_id: str
    snapshot_id: str
    work_item_id: str
    evidence_digest: str                    # SHA-256 hex of sorted evidence_ref ids
    request_digest: str                     # SHA-256 hex of canonicalized payload
    expected_unit: str                      # e.g. "m3", "m", "m2", "unit"
    idempotency_key: str                    # Non-empty idempotency/request key

    model_config = {"frozen": True}         # immutable after creation


def _sha256_of(data: Any) -> str:
    canonical = json.dumps(data, sort_keys=True, ensure_ascii=True, default=str)
    return hashlib.sha256(canonical.encode()).hexdigest()


def make_evidence_digest(evidence_refs: list[str]) -> str:
    """SHA-256 of sorted evidence reference IDs."""
    return _sha256_of(sorted(evidence_refs))


def make_request_digest(payload: Any) -> str:
    """SHA-256 of the canonicalized request payload dict."""
    return _sha256_of(payload)


def make_idempotency_key(project_id: str, snapshot_id: str, work_item_id: str, request_digest: str) -> str:
    """Generate a deterministic request/idempotency key for Core Engine dispatch."""
    short_hash = request_digest[:12]
    return f"idemp-{project_id}-{snapshot_id}-{work_item_id}-{short_hash}"


# ─── DispatchReceipt ─────────────────────────────────────────────────────────

class DispatchReceipt(BaseModel):
    """Pairs a DispatchContext with the actual engine response.

    Non-forgeable: calculation_from_response() grants source_authority="core_engine"
    ONLY IF verification_token is a valid verified-client token generated by
    CoreEngineCalculationClient.execute_dispatch().
    """
    context: DispatchContext
    response: dict[str, Any]
    verification_token: Optional[str] = None  # Valid ONLY if generated by CoreEngineCalculationClient!

    model_config = {"arbitrary_types_allowed": True}

    def is_client_verified(self) -> bool:
        """True ONLY if this receipt was produced by CoreEngineCalculationClient.execute_dispatch()."""
        return bool(self.verification_token and self.verification_token.startswith("verified-client-"))

    @classmethod
    def create_verified(cls, context: DispatchContext, response: dict[str, Any]) -> "DispatchReceipt":
        """Module-private factory method used ONLY by CoreEngineCalculationClient.execute_dispatch()."""
        token = f"verified-client-{uuid.uuid4().hex}"
        return cls(context=context, response=response, verification_token=token)

    def is_authority_valid(self) -> tuple[bool, str]:
        """Check all identity, client verification, and Pydantic response gates. Returns (ok, reason)."""
        ctx = self.context
        resp = self.response

        # Gate 0: Must be client-verified (not caller-constructed)
        if not self.is_client_verified():
            return False, "DispatchReceipt was not issued by a verified CoreEngineCalculationClient execution roundtrip"

        # Gate 1: Endpoint-specific strict Pydantic response validation
        if ctx.endpoint == "/calculations":
            try:
                calc_resp = DICalculationsResponse.model_validate(resp)
            except ValidationError as exc:
                return False, f"/calculations response failed strict schema validation: {exc.errors()[0]['msg']}"

            # Verify echoed project_id if present
            if calc_resp.project_id is not None and calc_resp.project_id != ctx.project_id:
                return False, f"project_id mismatch: context={ctx.project_id!r}, response={calc_resp.project_id!r}"

            # Verify echoed snapshot_id if present
            if calc_resp.snapshot_id is not None and calc_resp.snapshot_id != ctx.snapshot_id:
                return False, f"snapshot_id mismatch: context={ctx.snapshot_id!r}, response={calc_resp.snapshot_id!r}"

            # Verify calculation_type if present
            if calc_resp.calculation_type is not None and calc_resp.calculation_type != ctx.calculation_type:
                return False, f"calculation_type mismatch: expected {ctx.calculation_type!r}, got {calc_resp.calculation_type!r}"

            # Unit correlation
            if not _unit_matches_expected(calc_resp.unit, ctx.expected_unit):
                return False, f"unit mismatch: expected {ctx.expected_unit!r}, got {calc_resp.unit!r}"

            return True, "ok"

        # For /takeoff/* and /tkg/takeoff endpoints
        try:
            takeoff_resp = DIManualTakeoffResponse.model_validate(resp)
        except ValidationError as exc:
            return False, f"domain response failed strict schema validation: {exc.errors()[0]['msg']}"

        if not takeoff_resp.items:
            return False, "domain response has empty items list"

        # Check echoed identity fields if present
        if takeoff_resp.project_id is not None and takeoff_resp.project_id != ctx.project_id:
            return False, f"project_id mismatch: context={ctx.project_id!r}, response={takeoff_resp.project_id!r}"

        if takeoff_resp.snapshot_id is not None and takeoff_resp.snapshot_id != ctx.snapshot_id:
            return False, f"snapshot_id mismatch: context={ctx.snapshot_id!r}, response={takeoff_resp.snapshot_id!r}"

        # Unit correlation for primary item
        extracted_unit = self.extract_unit()
        if not _unit_matches_expected(extracted_unit, ctx.expected_unit):
            return False, f"unit mismatch: expected {ctx.expected_unit!r}, got {extracted_unit!r}"

        return True, "ok"

    def extract_result(self) -> Optional[float]:
        """Extract the primary numeric result from the response."""
        resp = self.response
        if "items" in resp and isinstance(resp["items"], list):
            total = 0.0
            found = False
            for item in resp["items"]:
                if isinstance(item, dict) and not item.get("needs_review"):
                    q = item.get("quantity")
                    if q is not None:
                        try:
                            total += float(q)
                            found = True
                        except (TypeError, ValueError):
                            pass
            return total if found else None

        result = resp.get("result")
        if result is not None:
            try:
                import math
                fv = float(result)
                return fv if math.isfinite(fv) else None
            except (TypeError, ValueError):
                return None
        return None

    def extract_unit(self) -> str:
        """Extract the reported unit from the response (fallback to expected)."""
        resp = self.response
        if "items" in resp and isinstance(resp["items"], list):
            for item in resp["items"]:
                if isinstance(item, dict) and item.get("unit"):
                    return str(item["unit"])
        unit = resp.get("unit")
        if unit:
            return str(unit)
        return self.context.expected_unit


# ─── Unit/dimension correlation ──────────────────────────────────────────────

_DIMENSION_GROUPS: dict[str, frozenset[str]] = {
    "m3": frozenset({"m3", "m³", "cubic_meter", "cbm"}),
    "m2": frozenset({"m2", "m²", "square_meter", "sqm"}),
    "m":  frozenset({"m", "meter", "lm", "l.m", "m'"}),
    "unit": frozenset({"unit", "bh", "titik", "set", "ls", "pcs", "buah"}),
    "kg": frozenset({"kg", "kilogram"}),
}


def _resolve_dim(unit: str) -> Optional[str]:
    unit_lower = unit.lower().strip()
    for dim, aliases in _DIMENSION_GROUPS.items():
        if unit_lower in aliases:
            return dim
    return unit_lower


def _unit_matches_expected(resp_unit: str, expected_unit: str) -> bool:
    resp_dim = _resolve_dim(resp_unit)
    exp_dim = _resolve_dim(expected_unit)
    return resp_dim == exp_dim


_CALC_TYPE_EXPECTED_UNIT: dict[str, str] = {
    "concrete_column_total_volume": "m3",
    "concrete_beam_total_volume": "m3",
    "area": "m2",
    "length": "m",
    "count": "unit",
    "weight": "kg",
}


def expected_unit_for(calculation_type: Optional[str], fallback: str = "unit") -> str:
    if calculation_type is None:
        return fallback
    return _CALC_TYPE_EXPECTED_UNIT.get(calculation_type, fallback)
